version: "3"
services:
    web:
        build: .
        ports:
            - "5001:5001"
            - "5000:5000"
        depends_on:
            - db
        environment:
          - ASPNETCORE_ENVIRONMENT=Local
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"