init_appservice:
	scripts/init.sh appservice

plan_appservice:
	scripts/plan.sh appservice

deploy_appservice:
	scripts/deploy.sh appservice $(ENVIRONMENT)
	
destroy_appservice:
	scripts/destroy.sh appservice
	

# init_database:
# 	scripts/init.sh database	

# init_queue:
# 	scripts/init.sh queue